# nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-nginx-deploy
  labels:
    app: front-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-nginx
  template:
    metadata:
      name: front-nginx
      labels:
        app: front-nginx
    spec:
      containers:
        - name: front-nginx
          image: dangdang42/front-nginx:v14
          ports:
            - containerPort: 80

---
# nignx
apiVersion: v1
kind: Service
metadata:
  name: front-nginx-svc
spec:
  selector:
    app: front-nginx
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30010