# nodejs
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-nodejs-deploy
  labels:
    app: front-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-nodejs
  template:
    metadata:
      name: front-nodejs
      labels:
        app: front-nodejs
    spec:
      containers:
        - name: front-nodejs
          image: dangdang42/front-nodejs:v32
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: front-secret

---
# nodejs
apiVersion: v1
kind: Service
metadata:
  name: front-nodejs-svc
spec:
  selector:
    app: front-nodejs
  ports:

    - port: 3000
      protocol: TCP
      targetPort: 3000
