apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_DATABASE: dWJ1bnR1
  MYSQL_USER: dWJ1bnR1
  MYSQL_PASSWORD: dWJ1bnR1
  MYSQL_ROOT_PASSWORD: dWJ1bnR1

---
apiVersion: v1
kind: Secret
metadata:
  name: front-secret
type: Opaque
data:
  #  REGIST_SRV_URL: bXNhLXJlZ2lzdGVyLXNlcnZpY2U6ODAwMA==  # msa-register-service:8000
  #  PAYMENT_SRV_URL: bXNhLXBheW1lbnQtc2VydmljZTo4MDAx  # msa-payment-service:8001
  #  PRODUCT_SRV_URL: bXNhLXByb2R1Y3Qtc2VydmljZTo4MDAy  # msa-product-service:8002
  #  STATISTICS_SRV_URL: bXNhLXN0YXRpc3RpY3Mtc2VydmljZTo4MDAz  # msa-statistics-service:8003
  #  REGIST_SRV_URL: MTkyLjE2OC41Ni4xOjMwMTAw  # 192.168.56.1:30100
  #  PAYMENT_SRV_URL: MTkyLjE2OC41Ni4xOjMwMzAw  # 192.168.56.1:30300
  #  PRODUCT_SRV_URL: MTkyLjE2OC41Ni4xOjMwNDAw  # 192.168.56.1:30400
  #  STATISTICS_SRV_URL: MTkyLjE2OC41Ni4xOjMwNTAw  # 192.168.56.1:30500
  REGIST_SRV_URL: bXNhLXJlZ2lzdGVyLXNlcnZpY2U6MzAxMDA=  # msa-register-service:30100
  PAYMENT_SRV_URL: bXNhLXBheW1lbnQtc2VydmljZTozMDMwMA==  # msa-payment-service:30300
  PRODUCT_SRV_URL: bXNhLXByb2R1Y3Qtc2VydmljZTozMDQwMA==  # msa-product-service:30400
  STATISTICS_SRV_URL: bXNhLXN0YXRpc3RpY3Mtc2VydmljZTozMDUwMA==  # msa-statistics-service:30500