apiVersion: v1
kind: Service
metadata:
  name: msa-register-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30100
  selector:
    app: msa-register-service
---
apiVersion: v1
kind: Service
metadata:
  name: msa-payment-service
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30300
  selector:
    app: msa-payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: msa-parking-service
spec:
  type: NodePort
  ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30400
  selector:
    app: msa-parking-service
---
apiVersion: v1
kind: Service
metadata:
  name: msa-statistics-service
spec:
  type: NodePort
  ports:
    - port: 8003
      targetPort: 8003
      nodePort: 30500
  selector:
    app: msa-statistics-service
