apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_DATABASE: dWJ1bnR1
  MYSQL_USER: dWJ1bnR1
  MYSQL_PASSWORD: dWJ1bnR1
  MYSQL_ROOT_PASSWORD: dWJ1bnR1

---
apiVersion: v1
kind: Secret
metadata:
  name: front-secret
type: Opaque
data:
  REGIST_SRV_URL: NDMuMjAzLjExMS4xMzg6MzAxMDA=
  PAYMENT_SRV_URL: NDMuMjAzLjExMS4xMzg6MzAzMDA=
  PRODUCT_SRV_URL: NDMuMjAzLjExMS4xMzg6MzA0MDA=
  STATISTICS_SRV_URL: NDMuMjAzLjExMS4xMzg6MzA1MDA=
