apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-register-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploy.app.register}}
  template:
    metadata:
      labels:
        app: {{ .Values.deploy.app.register}}
    spec:
      initContainers:
        - name: wait-for-mariadb
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 mariadb-service 3306; do echo 'Waiting for mariadb...'; sleep 5; done;"
      containers:
        - name: {{ .Values.deploy.app.register}}
          image: {{ .Values.imgs.REGIST_IMG }} # yoon741/msa_register_service:v2
          ports:
            - containerPort: {{ .Values.deploy.port.register}}
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mariadb.name }}  # Secret 이름
                  key: MYSQL_USER  # Secret 키
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mariadb.name }}
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mariadb.name }}
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: {{ .Values.maraidb.name }}
            - name: MYSQL_PORT
              value: "3306"
            - name: CORS_ORIGINS
              value: "http://{{ .Values.url.ip }}:{{ .Values.url.port.frontend }},http://front-nodejs-svc:3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-payment-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploy.app.payment}}
  template:
    metadata:
      labels:
        app: {{ .Values.deploy.app.payment}}
    spec:
      initContainers:
        - name: wait-for-mariadb
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 mariadb-service 3306; do echo 'Waiting for mariadb...'; sleep 5; done;"
      containers:
        - name: {{ .Values.deploy.app.payment}}
          image: {{ .Values.imgs.PAYMENT_IMG }}  # ashashrain/parking-payment-service:v6
          ports:
            - containerPort: {{ .Values.deploy.port.payment}}
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mariadb.name }}  # Secret 이름
                  key: MYSQL_USER  # Secret 키
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mariadb.name }}
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mariadb.name }}
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: {{ .Values.maraidb.name }}
            - name: MYSQL_PORT
              value: "3306"
            - name: CORS_ORIGINS
              value: "http://{{ .Values.url.ip }}:{{ .Values.url.port.frontend }},http://front-nodejs-svc:3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-product-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploy.app.product}}
  template:
    metadata:
      labels:
        app: {{ .Values.deploy.app.product}}
    spec:
      initContainers:
        - name: wait-for-mariadb
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 mariadb-service 3306; do echo 'Waiting for mariadb...'; sleep 5; done;"
      containers:
        - name: {{ .Values.deploy.app.product}}
          image: {{ .Values.imgs.PARKING_IMG }}  # docdker/parking:v2
          ports:
            - containerPort: {{ .Values.deploy.port.product }}
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mariadb.name }}  # Secret 이름
                  key: MYSQL_USER  # Secret 키
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mariadb.name }}
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mariadb.name }}
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: {{ .Values.maraidb.name }}
            - name: MYSQL_PORT
              value: "3306"
            - name: CORS_ORIGINS
              value: "http://{{ .Values.url.ip }}:{{ .Values.url.port.frontend }},http://front-nodejs-svc:3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-statistics-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploy.app.statistics}}
  template:
    metadata:
      labels:
        app: {{ .Values.deploy.app.statistics}}
    spec:
      initContainers:
        - name: wait-for-mariadb
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 mariadb-service 3306; do echo 'Waiting for mariadb...'; sleep 5; done;"
      containers:
        - name: {{ .Values.deploy.app.statistics}}
          #image: snicuz0588/msa-statistics-service:v7  # 이미지 이름 수정
          image: {{ .Values.imgs.STATISTICS_IMG }} # dangdang42/statistics:v2
          ports:
            - containerPort: {{ .Values.deploy.port.statistics}}
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret  # Secret 이름
                  key: MYSQL_USER  # Secret 키
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mariadb.name }}
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: {{ .Values.maraidb.name }}
            - name: MYSQL_PORT
              value: "3306"
            - name: CORS_ORIGINS
              value: "http://{{ .Values.url.ip }}:{{ .Values.url.port.frontend }},http://front-nodejs-svc:3000"