apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-nginx-deploy
  labels:
    app: front-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-nginx
  template:
    metadata:
      name: front-nginx
      labels:
        app: front-nginx
    spec:
      initContainers:
        - name: wait-for-mariadb
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 front-nodejs-svc 3000; do echo 'Waiting for nodejs...'; sleep 5; done;"
      containers:
        - name: front-nginx
          image: docker.io/yoon741/msa_frontend_nodejs:${DOCKER_BUILD_TAG}
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-nodejs-deploy
  labels:
    app: front-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-nodejs
  template:
    metadata:
      name: front-nodejs
      labels:
        app: front-nodejs
    spec:
      initContainers:
        - name: wait-for-mariadb
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 msa-statistics-service 8003; do echo 'Waiting for statistics-service...'; sleep 5; done;"
      containers:
        - name: front-nodejs
          image:  docker.io/yoon741/msa_frontend_nginx:${DOCKER_BUILD_TAG}
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: front-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-register-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-register-service
  template:
    metadata:
      labels:
        app: msa-register-service
    spec:
      initContainers:
        - name: wait-for-mariadb
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 mariadb-service 3306; do echo 'Waiting for mariadb...'; sleep 5; done;"
      containers:
        - name: msa-register-service
          image: docker.io/yoon741/msa_register_service:${DOCKER_BUILD_TAG}
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: "mariadb-service"
            - name: MYSQL_PORT
              value: "3306"
            - name: CORS_ORIGINS
              value: "http://15.164.235.17:30010,http://front-nodejs-svc:3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-payment-service
  template:
    metadata:
      labels:
        app: msa-payment-service
    spec:
      initContainers:
        - name: wait-for-mariadb
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 mariadb-service 3306; do echo 'Waiting for mariadb...'; sleep 5; done;"
      containers:
        - name: msa-payment-service
          image: docker.io/yoon741/msa_payment_service:${DOCKER_BUILD_TAG}
          ports:
            - containerPort: 8001
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: "mariadb-service"
            - name: MYSQL_PORT
              value: "3306"
            - name: CORS_ORIGINS
              value: "http://15.164.235.17:30010,http://front-nodejs-svc:3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-parking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-parking-service
  template:
    metadata:
      labels:
        app: msa-parking-service
    spec:
      initContainers:
        - name: wait-for-mariadb
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 mariadb-service 3306; do echo 'Waiting for mariadb...'; sleep 5; done;"
      containers:
        - name: msa-parking-service
          image: docker.io/yoon741/msa_parking_service:${DOCKER_BUILD_TAG}
          ports:
            - containerPort: 8002
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: "mariadb-service"
            - name: MYSQL_PORT
              value: "3306"
            - name: CORS_ORIGINS
              value: "http://15.164.235.17:30010,http://front-nodejs-svc:3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-statistics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-statistics-service
  template:
    metadata:
      labels:
        app: msa-statistics-service
    spec:
      initContainers:
        - name: wait-for-mariadb
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 mariadb-service 3306; do echo 'Waiting for mariadb...'; sleep 5; done;"
      containers:
        - name: msa-statistics-service
          image: docker.io/yoon741/msa_statistics_service:${DOCKER_BUILD_TAG}
          ports:
            - containerPort: 8003
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: "mariadb-service"
            - name: MYSQL_PORT
              value: "3306"
            - name: CORS_ORIGINS
              value: "http://15.164.235.17:30010,http://front-nodejs-svc:3000"
