apiVersion: v1
kind: Service
metadata:
  name: msa-register-service
spec:
  type: NodePort  # 외부에서 접근 가능하도록 설정
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30100  # 원하는 노드 포트 (선택 사항)
  selector:
    app: msa-register
---
apiVersion: v1
kind: Service
metadata:
  name: msa-payment-service
spec:
  type: NodePort  # 외부에서 접근 가능하도록 설정
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30300  # 원하는 노드 포트 (선택 사항)
  selector:
    app: msa-payment
---
apiVersion: v1
kind: Service
metadata:
  name: msa-product-service
spec:
  type: NodePort  # 외부에서 접근 가능하도록 설정
  ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30400  # 원하는 노드 포트 (선택 사항)
  selector:
    app: msa-product
---
apiVersion: v1
kind: Service
metadata:
  name: msa-statistics-service
spec:
  type: NodePort  # 외부에서 접근 가능하도록 설정
  ports:
    - port: 8003
      targetPort: 8003
      nodePort: 30500  # 원하는 노드 포트 (선택 사항)
  selector:
    app: msa-statistics