apiVersion: v1
kind: Service
metadata:
  name: msa-register-service
spec:
  type: NodePort  # 외부에서 접근 가능하도록 설정
  ports:
    - port: {{ .Values.deploy.port.register }}
      targetPort: {{ .Values.deploy.port.register }}
      nodePort: 30100  # 원하는 노드 포트 (선택 사항)
  selector:
    app: {{ .Values.deploy.app.register }}
---
apiVersion: v1
kind: Service
metadata:
  name: msa-payment-service
spec:
  type: NodePort  # 외부에서 접근 가능하도록 설정
  ports:
    - port: {{ .Values.deploy.port.payment }}
      targetPort: {{ .Values.deploy.port.payment }}
      nodePort: 30300  # 원하는 노드 포트 (선택 사항)
  selector:
    app: {{ .Values.deploy.app.payment }}
---
apiVersion: v1
kind: Service
metadata:
  name: msa-product-service
spec:
  type: NodePort  # 외부에서 접근 가능하도록 설정
  ports:
    - port: {{ .Values.deploy.port.product }}
      targetPort: {{ .Values.deploy.port.product }}
      nodePort: 30400  # 원하는 노드 포트 (선택 사항)
  selector:
    app: {{ .Values.deploy.app.product }}
---
apiVersion: v1
kind: Service
metadata:
  name: msa-statistics-service
spec:
  type: NodePort  # 외부에서 접근 가능하도록 설정
  ports:
    - port: {{ .Values.deploy.port.statistics}}
      targetPort: {{ .Values.deploy.port.statistics}}
      nodePort: 30500  # 원하는 노드 포트 (선택 사항)
  selector:
    app: {{ .Values.deploy.app.statistics }}